spring:
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/myproject?serverTimezone=GMT%2B8
        username: root
        password: root
mybatis:
     type-aliases-package: com.bxkj.bxkjtao.entry
     mapper-locations: classpath:mapper/*.xml